s = set()
n = input('please enter a integer')
s.add(int(n))
n = input('please enter a integer')
s.add(int(n))
n = input('please enter a integer')
s.add(int(n))
n = input('please enter a integer')
s.add(int(n))
n = input('please enter a integer')
s.add(int(n))
n = input('please enter a integer')
s.add(int(n))
n = input('please enter a integer')
s.add(int(n))
n = input('please enter a integer')
s.add(int(n))
print(s)

s = set()
s.add(20)
s.add(20.0)
s.add('20')
print(s)     #it is an imp question for interviews in python 20 == 20.0 int is equal to a float value if numerical is same if they ask len then it is only 2 not 3
print(len(s),type(s))